### ISSUE TITLE
Question: ESP32 enclosure

### ISSUE THREAD

**Issue by w00dst0ck** [Yogui79/IntexPureSpa#18]
Question: Do you have a recommendation for an ESP32 enclosure?
Frage: Habt Ihr eine Empfehlung für ein ESP32 Gehäuse?

BTW: Cooles Projekt!

**Comment by LEECHER1** [comment]
I bought this case from Conrad Austria.  I think it's pretty good approx. 4 € 
The USB hole is selfmade. ;)

![IMG_20210224_185020](https://user-images.githubusercontent.com/12032696/126167820-7b9a9de6-a181-4016-a646-d8e758a08b74.jpg)

**Comment by w00dst0ck** [comment]
Thank you for the fast reply
